# Generated by Django 5.1.4 on 2024-12-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_karachi_buildings_survey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karachi_buildings',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
