# Generated by Django 5.1.4 on 2024-12-30 10:21

import django.contrib.gis.db.models.fields
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_karachi_buildings_survey_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('select_city', models.CharField(choices=[('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Nawabshah', 'Nawabshah'), ('Larkana', 'Larkana'), ('Sukkur', 'Sukkur')], default='Karachi', max_length=100)),
                ('Building_Code', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('building_type', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Office', 'Office'), ('Hotel', 'Hotel'), ('Health', 'Health'), ('Mall', 'Mall'), ('Educational', 'Educational'), ('Other Buildings', 'Other Buildings')], max_length=254, null=True)),
                ('building', models.CharField(blank=True, max_length=254, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('built_up_area', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('google_pin', models.URLField(blank=True, max_length=500, null=True)),
                ('architect_developer', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Documents Awaited', 'Documents Awaited'), ('In progress', 'In progress'), ('Permission Awaited', 'Permission Awaited'), ('Permission granted', 'Permission granted'), ('N/A', 'N/A')], max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=home.models.SurveyProgress.upload_to_city_folder)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('survey_lead', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Karachi_Buildings',
        ),
    ]
