# Generated by Django 5.1.4 on 2024-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_surveyprogress_delete_karachi_buildings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyprogress',
            name='select_city',
            field=models.CharField(choices=[('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Nawabshah', 'Nawabshah'), ('Larkana', 'Larkana'), ('Sukkur', 'Sukkur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyprogress',
            name='survey_lead',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
