# Generated by Django 5.1.4 on 2025-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_surveyprogress_select_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_for_building', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('weather', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField()),
                ('surveyor_name', models.CharField(max_length=100)),
                ('surveyor_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('respondent_name', models.CharField(max_length=100)),
                ('respondent_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('building_type', models.CharField(choices=[('Residential', 'Residential'), ('Office', 'Office'), ('Hotel/Cultural Centre', 'Hotel/Cultural Centre'), ('Health', 'Health'), ('Mall', 'Mall'), ('Educational', 'Educational')], max_length=30)),
                ('building_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_contact_no', models.CharField(max_length=15)),
                ('city_zone', models.CharField(max_length=100)),
                ('total_residents', models.PositiveIntegerField(blank=True, null=True)),
                ('total_plot_area', models.FloatField()),
                ('total_built_area', models.FloatField()),
                ('floors_ground', models.PositiveIntegerField()),
                ('floors_basement', models.PositiveIntegerField(blank=True, null=True)),
                ('year_of_construction', models.PositiveIntegerField()),
                ('total_rooms_units', models.PositiveIntegerField()),
                ('architect', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('executive_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('deluxe_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('meeting_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('offices', models.PositiveIntegerField(blank=True, null=True)),
                ('shops', models.PositiveIntegerField(blank=True, null=True)),
                ('restaurants', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveIntegerField(blank=True, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('building_dimensions', models.TextField(blank=True, null=True)),
                ('transformer_capacity', models.FloatField(blank=True, null=True)),
                ('single_access_point', models.BooleanField(default=False)),
                ('multiple_access_points', models.PositiveIntegerField(blank=True, null=True)),
                ('ground_floor_height', models.FloatField()),
                ('first_floor_height', models.FloatField()),
                ('basement_height', models.FloatField(blank=True, null=True)),
                ('total_height', models.FloatField()),
                ('electricity_consumption', models.FloatField(blank=True, null=True)),
                ('renewable_energy_installed', models.BooleanField(default=False)),
                ('renewable_energy_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
