# Generated by Django 5.1.4 on 2025-01-03 05:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_buildingsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingsurvey',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='buildingsurvey',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingsurvey',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
